### ISSUE TITLE
Problem Garbage Job - Return Vehicle

### ISSUE THREAD

**Issue by XianPT** [GouveiaXS/angelicxs-CivilianJobs#1]
Used Ox_Target

Print error

https://prnt.sc/GYOUFDN7oEFT

**Comment by GouveiaXS** [comment]
What happened or didnt happen?

**Comment by XianPT** [comment]
yes this error happened and still continues

**Comment by GouveiaXS** [comment]
You didn't answer the question. I see the error you provided but you didn't give any details on what caused it to occur or if anything broke.

**Comment by XianPT** [comment]
Sorry, I thought I saw the title.

It's when I start the job but I don't even start the route, I just go to deliver the truck through the target and it gives this error .

**Comment by GouveiaXS** [comment]
Issue should have been resolved in updates since last message.
