### ISSUE TITLE
need help :(

### ISSUE THREAD

**Issue by Deathdomain** [GouveiaXS/angelicxs-CivilianJobs#2]
no such export setfuel in resource ox_fuel is a error im getting :(

**Comment by GouveiaXS** [comment]
its not an export. ox fuel uses state bags.
as per their documentation it should be

Entity(vehicle).state.fuel = 100

**Comment by Deathdomain** [comment]
and how do i get the vehicles to all spawn with 100 fuel? sorry im new to this stuff and it might help someone also

**Comment by GouveiaXS** [comment]
that should make it so the vehicles spawn with 100% fuel. I am not familiar with ox_fuel so you many need to ask them the exact thing you need.
It just needs to be put in the event noted in the config (replacing the example ps-fuel one).

**Comment by Deathdomain** [comment]
> 

so i put Entity(vehicle).state.fuel = 100 next to exports["ox_fuel"] correct?

because im getting this now

SCRIPT ERROR: @angelicxs-CivilianJobs/config.lua:78: No such export Entity in resource ox_fuel
handler (@angelicxs-CivilianJobs/client/main.lua:148)

**Comment by GouveiaXS** [comment]
As noted before ox_fuel does not use exports. You will need to remove the following export entirely:
exports["ox_fuel"]

**Comment by QuarterMileRP** [comment]
if it helps, this worked for me:
AddEventHandler('angelicxs-CivilianJobs:VehicleInitation', function(vehicle)
	
	
	TriggerEvent("vehiclekeys:client:SetOwner", GetVehicleNumberPlateText(vehicle))
    local Vehicle = Entity(vehicle).state
	Vehicle:set('fuel', 100, true)
	SetVehicleFuelLevel(vehicle, 100)
	end)

**Comment by GouveiaXS** [comment]
The proper code fro gas using ox_fuel:

AddEventHandler('angelicxs-CivilianJobs:VehicleInitation', function(vehicle)
  Entity(vehicle).state.fuel = 100
end)
