### ISSUE TITLE
Keys And Fuel

### ISSUE THREAD

**Issue by Blanco0918** [GouveiaXS/angelicxs-CivilianJobs#3]
Im having trouble trying to set the event for ox_fuel and loaf_keysystem, would you by any chance be able to help?

**Comment by GouveiaXS** [comment]
To add ox_fuel:
```
AddEventHandler('angelicxs-CivilianJobs:VehicleInitation', function(vehicle)
  Entity(vehicle).state.fuel = 100
end)
```

I am unaware of that key-system, you would need to reach out to them to figure out the correct exports.
