### ISSUE TITLE
I keep getting this bug

### ISSUE THREAD

**Issue by JasonNolimit** [GouveiaXS/angelicxs-CivilianJobs#5]
if someone has a active job and they havent returned the vehicle from the first job and they try to get a vehicle from a second job it removes peds from other job locations and gives error

A second ped spawn has automatically been aborted, requesting eventor:

Is there a way to make it so if you choose to start a new job the previous jobs vehicle gets removed

**Comment by GouveiaXS** [comment]
If you turn vehicle steward off in the config this should fix your issue.
